// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    404: typeof import('./src/components/errorpage/404.vue')['default']
    500: typeof import('./src/components/errorpage/500.vue')['default']
    ACol: typeof import('ant-design-vue/es')['Col']
    AInput: typeof import('ant-design-vue/es')['Input']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutFooter: typeof import('ant-design-vue/es')['LayoutFooter']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    ARow: typeof import('ant-design-vue/es')['Row']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    Card: typeof import('./src/components/Card.vue')['default']
    CardList: typeof import('./src/components/CardList.vue')['default']
    ComingSoon: typeof import('./src/components/ComingSoon.vue')['default']
    HeaderInput: typeof import('./src/components/HeaderInput.vue')['default']
    IbcFooter: typeof import('./src/components/IbcFooter.vue')['default']
    LayerBlock: typeof import('./src/components/LayerBlock.vue')['default']
    Navigation: typeof import('./src/components/Navigation.vue')['default']
    NoDatas: typeof import('./src/components/NoDatas.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
