// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    404: typeof import('./src/components/errorpage/404.vue')['default']
    500: typeof import('./src/components/errorpage/500.vue')['default']
    Base: typeof import('./src/components/responsive/dropdown/base.vue')['default']
    BottomStatus: typeof import('./src/components/responsive/table/bottomStatus.vue')['default']
    ChainIcon: typeof import('./src/components/responsive/table/chainIcon.vue')['default']
    Chains: typeof import('./src/components/responsive/dropdown/chains.vue')['default']
    ComingSoon: typeof import('./src/components/ComingSoon.vue')['default']
    CopyComponent: typeof import('./src/components/CopyComponent.vue')['default']
    HeaderInput: typeof import('./src/components/HeaderInput.vue')['default']
    IbcFooter: typeof import('./src/components/IbcFooter.vue')['default']
    IconAndTitle: typeof import('./src/components/responsive/table/iconAndTitle.vue')['default']
    LayerBlock: typeof import('./src/components/LayerBlock.vue')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    MaintenancePage: typeof import('./src/components/MaintenancePage.vue')['default']
    Navigation: typeof import('./src/components/Navigation.vue')['default']
    NoDatas: typeof import('./src/components/NoDatas.vue')['default']
    PageContainer: typeof import('./src/components/responsive/pageContainer.vue')['default']
    PageTitle: typeof import('./src/components/responsive/pageTitle.vue')['default']
    ResetButton: typeof import('./src/components/responsive/resetButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatusImg: typeof import('./src/components/responsive/table/statusImg.vue')['default']
    Table: typeof import('./src/components/responsive/table/index.vue')['default']
    TokenIcon: typeof import('./src/components/responsive/table/tokenIcon.vue')['default']
    Tokens: typeof import('./src/components/responsive/dropdown/tokens.vue')['default']
    TransferTxs: typeof import('./src/components/responsive/table/transferTxs.vue')['default']
  }
}

export {}
