export const GET_IBCSTATISTICS = 'GET_IBCSTATISTICS';
export const GET_IBCDENOMS = 'GET_IBCDENOMS';
export const GET_IBCBASEDENOMS = 'GET_IBCBASEDENOMS';
export const GET_IBCCHAINS = 'GET_IBCCHAINS';
export const GET_IBCCONFIGS = 'GET_IBCCONFIGS';
export const GET_IBCTXS = 'GET_IBCTXS';