export const SET_IBCSTATISTICS_CHAINS = 'SET_IBCSTATISTICS_CHAINS';
export const SET_IBCSTATISTICS_CHANNELS = 'SET_IBCSTATISTICS_CHANNELS';
export const SET_IBCSTATISTICS_DENOMS = 'SET_IBCSTATISTICS_DENOMS';
export const SET_IBCSTATISTICS_TXS = 'SET_IBCSTATISTICS_TXS';
export const SET_IBCDENOMS = 'SET_IBCDENOMS';
export const SET_IBCBASEDENOMS = 'SET_IBCBASEDENOMS';
export const SET_IBCCHAINS = 'SET_IBCCHAINS';
export const SET_IBCCONFIGS = 'SET_IBCCONFIGS';
