// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    404: typeof import('./../components/errorpage/404.vue')['default']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AInput: typeof import('ant-design-vue/es')['Input']
    AList: typeof import('ant-design-vue/es')['List']
    AListItem: typeof import('ant-design-vue/es')['ListItem']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    APagination: typeof import('ant-design-vue/es')['Pagination']
    APopover: typeof import('ant-design-vue/es')['Popover']
    ARangePicker: typeof import('ant-design-vue/es')['RangePicker']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    ATypographyText: typeof import('ant-design-vue/es')['TypographyText']
    BaseDropdown: typeof import('./../components/responsive/dropdown/BaseDropdown.vue')['default']
    BjSelect: typeof import('./../components/BjSelect/index.vue')['default']
    BottomStatus: typeof import('./../components/responsive/table/BottomStatus.vue')['default']
    ChainIcon: typeof import('./../components/responsive/table/ChainIcon.vue')['default']
    ChainsDropdown: typeof import('./../components/responsive/dropdown/ChainsDropdown.vue')['default']
    ComingSoon: typeof import('./../components/ComingSoon.vue')['default']
    CopyComponent: typeof import('./../components/CopyComponent.vue')['default']
    Error500: typeof import('./../components/errorpage/Error500.vue')['default']
    HeaderInput: typeof import('./../components/HeaderInput.vue')['default']
    IbcFooter: typeof import('./../components/IbcFooter.vue')['default']
    IbcHeader: typeof import('./../components/IbcHeader.vue')['default']
    IconAndTitle: typeof import('./../components/responsive/table/IconAndTitle.vue')['default']
    Loading: typeof import('./../components/Loading.vue')['default']
    Navigation: typeof import('./../components/Navigation.vue')['default']
    NoDatas: typeof import('./../components/NoDatas.vue')['default']
    PageContainer: typeof import('./../components/responsive/PageContainer.vue')['default']
    PageTitle: typeof import('./../components/responsive/PageTitle.vue')['default']
    ResetButton: typeof import('./../components/responsive/ResetButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShowBase: typeof import('./../components/BjSelect/mode/ShowBase.vue')['default']
    ShowDouble: typeof import('./../components/BjSelect/mode/ShowDouble.vue')['default']
    StatusImg: typeof import('./../components/responsive/table/StatusImg.vue')['default']
    TableCommon: typeof import('./../components/responsive/table/TableCommon.vue')['default']
    TokenIcon: typeof import('./../components/responsive/table/TokenIcon.vue')['default']
    TokensDropdown: typeof import('./../components/responsive/dropdown/TokensDropdown.vue')['default']
    TransferTxs: typeof import('./../components/responsive/table/TransferTxs.vue')['default']
  }
}

export {}
