// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core';

declare module '@vue/runtime-core' {
    export interface GlobalComponents {
        404: typeof import('./../components/errorpage/404.vue')['default'];
        500: typeof import('./../components/errorpage/500.vue')['default'];
        ABadge: typeof import('ant-design-vue/es')['Badge'];
        AButton: typeof import('ant-design-vue/es')['Button'];
        AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider'];
        ADropdown: typeof import('ant-design-vue/es')['Dropdown'];
        AInput: typeof import('ant-design-vue/es')['Input'];
        ALayout: typeof import('ant-design-vue/es')['Layout'];
        ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent'];
        ALayoutFooter: typeof import('ant-design-vue/es')['LayoutFooter'];
        ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader'];
        AMenu: typeof import('ant-design-vue/es')['Menu'];
        AMenuItem: typeof import('ant-design-vue/es')['MenuItem'];
        APagination: typeof import('ant-design-vue/es')['Pagination'];
        APopover: typeof import('ant-design-vue/es')['Popover'];
        ARangePicker: typeof import('ant-design-vue/es')['RangePicker'];
        ASelect: typeof import('ant-design-vue/es')['Select'];
        ASelectOption: typeof import('ant-design-vue/es')['SelectOption'];
        ASpin: typeof import('ant-design-vue/es')['Spin'];
        ATable: typeof import('ant-design-vue/es')['Table'];
        BottomStatus: typeof import('./../components/responsive/table/bottomStatus.vue')['default'];
        ChainIcon: typeof import('./../components/responsive/table/chainIcon.vue')['default'];
        ComingSoon: typeof import('./../components/ComingSoon.vue')['default'];
        CopyComponent: typeof import('./../components/CopyComponent.vue')['default'];
        DropDownBase: typeof import('./../components/responsive/dropdown/DropDownBase.vue')['default'];
        DropDownChains: typeof import('./../components/responsive/dropdown/DropDownChains.vue')['default'];
        DropDownTokens: typeof import('./../components/responsive/dropdown/DropDownTokens.vue')['default'];
        HeaderInput: typeof import('./../components/HeaderInput.vue')['default'];
        IbcFooter: typeof import('./../components/IbcFooter.vue')['default'];
        IconAndTitle: typeof import('./../components/responsive/table/iconAndTitle.vue')['default'];
        Loading: typeof import('./../components/Loading.vue')['default'];
        Navigation: typeof import('./../components/Navigation.vue')['default'];
        NoDatas: typeof import('./../components/NoDatas.vue')['default'];
        PageContainer: typeof import('./../components/responsive/pageContainer.vue')['default'];
        PageTitle: typeof import('./../components/responsive/pageTitle.vue')['default'];
        ResetButton: typeof import('./../components/responsive/resetButton.vue')['default'];
        RouterLink: typeof import('vue-router')['RouterLink'];
        RouterView: typeof import('vue-router')['RouterView'];
        StatusImg: typeof import('./../components/responsive/table/statusImg.vue')['default'];
        Table: typeof import('./../components/responsive/table/index.vue')['default'];
        TokenIcon: typeof import('./../components/responsive/table/tokenIcon.vue')['default'];
        TransferTxs: typeof import('./../components/responsive/table/transferTxs.vue')['default'];
    }
}

export {};
